### ISSUE TITLE
add possibility to customize default num replicas

### ISSUE THREAD

**Issue by BrunoBonacci** [samsara/samsara#13]

**Comment by DayoOliyide** [comment]
Any reason why the elasticsearch `index.number_of_replicas` setting is currently 2 instead of the
default 1 ?

**Comment by BrunoBonacci** [comment]
Defaults are suitable for production clusters. On production clusters we have everything Replicated 3 times. Two copies aren't enough?

**Comment by DayoOliyide** [comment]
That's fine. :+1:
