### ISSUE TITLE
kv-store topics in kafka MUST be compacted

### ISSUE THREAD

**Issue by BrunoBonacci** [samsara/samsara#16]
Samsara core should ensure these topics are always compacted

Here a way how to create a topic programmatically
http://stackoverflow.com/questions/16946778/how-can-we-create-a-topic-in-kafka-from-the-ide-using-api

**Comment by DayoOliyide** [comment]
@BrunoBonacci having a look at this.
Relatively simple, just adding a function that will conditionally create compacted topics
within the [utils namespace](https://github.com/samsara/samsara/blob/master/core/src/samsara_core/utils.clj)

Just want to confirm that the [send-txlog-topic](https://github.com/samsara/samsara/blob/master/core/src/samsara_core/utils.clj#L55), [send-kvstore-to-topic](https://github.com/samsara/samsara/blob/master/core/src/samsara_core/utils.clj#L71) and [ bootstrap-dimension-from-file](https://github.com/samsara/samsara/blob/master/core/src/samsara_core/utils.clj#L79) functions aren't yet being used. I can't see any use of them anywhere at the moment

**Comment by BrunoBonacci** [comment]
yes, these functions are used by the samsara-core user to create and bootstrap dimensions.

I don't think you can fully resolve this ticket until we got completely rid of samza execution layer in favour of our custom executor + your kafka library.

One place you could start is by creating a function in core/utils like 
`(ensure-topic "my-kv-topic" :compact true) ` 
and making sure that it is called before starting samza using the config.

https://github.com/samsara/samsara/blob/master/core/src/samsara_core/main.clj#L222


The functions  `send-txlog-topic`, `send-kvstore-to-topic` and `bootstrap-dimension-from-file` are mainly used offline for data preparation.

**Comment by BrunoBonacci** [comment]
The idea behind these function is to convert another datasource (such as your existing SQL USERS database into a Samsara's k/v-store where you can lookup users by id. Once in this form you can use the tx-log function to produce a feed which can be saved into a topic and used as additional data-source "dimensions") in your stream processing for example to enrich the users details in the incoming events.

Probably need more work to package them properly :-(

**Comment by DayoOliyide** [comment]
Understood.
But to be sure, :eyes: on [115064d](https://github.com/samsara/samsara/commit/115064d1c6453721b2b535bf1de6530023ff1a4b)
