### ISSUE TITLE
add Python client

### ISSUE THREAD

**Issue by BrunoBonacci** [samsara/samsara#2]
The general design of all clients is based on a two levels API. Although the aim is to make idiomatic clients for every language we want to keep an high level design common across all clients, given that the language primitives offers the required capabilities.
## Lower level API (`publish-events`)

The first lower level it is just a wrapper on top of the communication protocol with the **ingestion-api** (HTTP POST). See the [ingestion-api spec](https://github.com/samsara/samsara/blob/master/ingestion-api/spec/ingestion-api-spec.yaml) for more info. 

The signature looks like: `publish-events(URL, List<Events>)`.  
At this stage the `publish-events` does the following three things:
- Validate events (check the existence and type of the three required keys for each event: **sourceId**, **timestamp** and **eventName**)
- create a JSON payload with all events
- optionally compress the payload (**gzip**)
- add the `X-Samsara-publishedTimestamp` HTTP header
- and finally performs the HTTP POST to the given endpoint URL
## Higher level API (`record-event`)

The second level is the buffering layer. For clients which wish to buffer locally the events before posting them to the ingestion-api we want to provide another API.
This api is called `record-event(Event)` and it takes a single event.
The job of this API is to validate the single event and add it to a in-memory [ring-buffer](https://en.wikipedia.org/wiki/Circular_buffer).
Periodically (configurable) a background thread takes the content of the ring buffer and publishes the events using the `publish-events` api.
The buffer can have a configurable size and if the buffer is full we currently implement only one strategy which is to drop the oldest events. In future we might add more strategies.
The major concern of this api is to provide a fast and thread-safe way to record the events in the buffer.
This API has to have good performance characteristics and use [CAS](https://en.wikipedia.org/wiki/Compare-and-swap) where possible (given that the language primitives allows it). We discourage the use of [mutex](https://en.wikipedia.org/wiki/Mutual_exclusion) as they can be an unnecessary burden for the system and cause excessive context switches. Contrarily CAS can run on user-space whereas mutex are coordinated by the kernel.

Once the background thread successfully publishes the events to the ingestion-api, it discards them from the ring-buffer. Clients must be careful to only discards events which have been sent. The HTTP POST might takes several hundreds of milliseconds up to a few seconds, during this time another thread might have recorded additional events in the buffer. Therefore is crucial to keep track of which event were sent and discard only these from the buffer.

The goal is to provide a common api for all languages where one can trust the behaviour of these two APIs. Developers of client libraries have to try to follow these guidelines and make clients as much idiomatic as possible for each language.

**Comment by puhrez** [comment]
Looking through the clojure and ios client, the principal spec for this is having a configurable client that can record events eh?

**Comment by puhrez** [comment]
that ingestion api spec link leads to a 404, here's one that'll work https://github.com/samsara/samsara/blob/master/ingestion-api/spec/ingestion-api-spec.yaml

**Comment by BrunoBonacci** [comment]
link fixed thanks

**Comment by puhrez** [comment]
I think the use of `collections.deque` instead of implementing a ring-buffer is the best choice. With it we get many CPython optimizations and the guarantee's of atomicity, re https://bugs.python.org/issue15329#msg199368.

**Comment by BrunoBonacci** [comment]
Hi Michael,

I don't much about python development but looking at
http://stackoverflow.com/questions/4151320/efficient-circular-buffer it
looks like the collections.deque can be limited and act like a ring-buffer.

The reason behind using a ring-buffer is to put an upper limit to the
memory consumption. The last thing we want is to cause a crash to the
hosting application if events are produced faster than they can be sent.

Things you need to careful are:

   - insertion should NEVER block: blocking insertion will cause producer
slow down, and we don't want that. If queue if full oldest event should be
dropped.
   - between the time you the thread starts packing and sending the content
of the buffer and the time it completes, more events could be added, so the
you should be careful remove only the events you published and not all of
them.

Bruno

**Comment by BrunoBonacci** [comment]
fixed by #62
