### ISSUE TITLE
Error on core dependencies download

### ISSUE THREAD

**Issue by ndrluis** [samsara/samsara#52]
```
$ lein deps
Could not find artifact samsara:moebius:jar:0.5.7.0-SNAPSHOT in clojars (https://clojars.org/repo/)
Could not find artifact samsara:samsara-utils:jar:0.5.7.0-SNAPSHOT in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

**Comment by BrunoBonacci** [comment]
@ndrluis `samsara-utils` is a sub-project of samsara (a library) and it is available https://github.com/samsara/samsara/tree/master/utils

Initially all sub-modules were separate project we recently migrated them into a single project to facilitate the dependency management and versioning.

In the master branch all dependencies are set to the next development version (SNAPSHOT),
and we typically don't deploy the SNAPSHOT version to clojars, we only push releases.

If _you wish to run the latest development version_ I'll recommend you to follow the instructions here.
http://samsara-analytics.io/docs/quick-start/#snapshot

if you want to build the master branch yourself i'll suggest to run:

```
cd samsara
./bin/build-all-projects.sh
```

This script should build and install locally all development artifacts.

I'll close this ticket for now, if you have further issues, please re-open it.
