### ISSUE TITLE
Timbre doesn't call toString() on objects

### ISSUE THREAD

**Issue by DayoOliyide** [samsara/samsara#54]
After [bumping Timbre to 4.0.2](https://github.com/samsara/samsara/commit/ed6306730b2980b7f1c7fb7e5afbc29a52368b02), I've noticed that when objects are passed to the logging fns (e.g info, debug) that they aren't printed in the same way (`toString()` being used) as before with `Timbre 3.4.0` version.

I suspect it's either a bug in `Timbre 4.0.2` , in `samsara.utils/log-fmt-fn` or a missing Timbre configuration.

I'm going to look into this over the next few days. 
This issue is just to let anyone else know that it's being looked into.

**Comment by DayoOliyide** [comment]
I've looked into this. The actual issue is that records `defrecord` and lazy seqs weren't being
printed. This has been fixed in [Timbre 4.2.0](https://github.com/ptaoussanis/timbre/releases/tag/v4.2.0).

To get this fix in (and other fixes), I've decided to bump timbre up to the latest version.

**Comment by BrunoBonacci** [comment]
hi,
I think that since we are updating the deps it would be better to use latest available

`[com.taoensso/timbre "4.5.1"]`
https://github.com/ptaoussanis/timbre

no point to update and use a old one.
